project:
    name: 'Computer Vision Service'
    version: '0.0.10'
database:
    name: 'cv_service.db'
server:
    address: '0.0.0.0'
    address_b: '10.33.22.113'
    port: 5000
    pytesseract_path: 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
image:
    default_size: '640x480'
models:
    emptybox:
        name: 'emptybox'
        graph: 'emptybox'
        size: 224
        channels: 3
        labels: ['OK', 'NOT_OK']   
    tanklabels:
        name: 'tanklabels'
        graph: 'tanklabels'
        size: 70
        channels: 1
        labels: ['1', '2', 'P', 'T', '1_180', '2_180', 'P_180', 'T_180', '1_90', '2_90', 'P_90', 'T_90']        
    default:
        name: 'default'
        graph: 'imagenet'
        size: 224
        channels: 3
        labels: []  
    Model2:
        name: 'Model2'          
        graph: 'model2.h5'
        size: 70
        channels: 1
        labels: ['OK']