debug: False
project:
    name: 'Computer Vision Service'
    version: '0.1.0'
database:
    name: 'cv_service.db'
    path: ''
server:
    address: '10.33.22.113'
    address_1: '10.33.22.113'
    address_2: ''
    port: 5000
    pytesseract_path: 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
    pytesseract_path_linux: 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
    image_save_path: '/Data'
    image_save_path_linux: '/tmp/Data/'    
image:
    default_size: '640x480'
models:
    path: './tf_models'
    graph_file: 'keras_model.h5'
